name: CI/CD

on:
  push:
    branches:
      - '**' # Runs on all branches

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: yarn install

      - name: Run Link CLI
        run: yarn link-cli

      - name: Run Prettier
        run: yarn format:check

      # Publish step only on master branch
      - name: Publish to NPM
        if: github.ref == 'refs/heads/master' # Ensure this runs only on master branch
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
